# Generated by Django 2.2.3 on 2021-03-28 10:32

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Template name')),
                ('nickname', models.CharField(blank=True, max_length=35, null=True, verbose_name='Template nickname')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='Contents/Post_gallery_images', verbose_name='Load image')),
            ],
            options={
                'verbose_name': 'Template name',
                'verbose_name_plural': 'Section templates',
                'unique_together': {('name', 'nickname')},
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='component_type',
        ),
        migrations.AlterField(
            model_name='generaldatalanguage',
            name='general_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Json content'),
        ),
        migrations.AlterField(
            model_name='menuitemlanguage',
            name='menu_item_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Json content'),
        ),
        migrations.AlterField(
            model_name='menulanguage',
            name='menu_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Json content'),
        ),
        migrations.AlterField(
            model_name='pagelanguage',
            name='page_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Json content'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='post_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Json content'),
        ),
        migrations.AlterField(
            model_name='sectionlanguage',
            name='sect_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Json content'),
        ),
        migrations.DeleteModel(
            name='ComponentType',
        ),
        migrations.AddField(
            model_name='section',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.SectionTemplate', verbose_name='Posts visualization component'),
        ),
    ]
