# ----------CONTENTS APP CONSTANTS----------#
APP_LABEL = 'contents'

DEFAULT_VALUE = '-'
PATH_APP = 'contents/'

MAX_LENGTH_20 = 20
MAX_LENGTH_50 = 50
MAX_LENGTH_NAME = 35
MAX_LENGTH_TITLE = 200
MAX_LENGTH_URL = 255
MAX_LENGTH_SHORT_TITLE = 100
ORDER_VALUE_DEFAULT = 0
