# Generated by Django 2.2.3 on 2021-04-23 03:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20210421_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.MenuItem', verbose_name='Menu item parent'),
        ),
    ]
