# Generated by Django 2.2.3 on 2021-04-11 06:19

import ckeditor.fields
import colorfield.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20210409_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaldatalanguage',
            name='main_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Menu', verbose_name='Main menu'),
        ),
        migrations.AlterField(
            model_name='generaldatalanguage',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='page',
            name='inner_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Menu', verbose_name='Page main menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Page', verbose_name='Page parent'),
        ),
        migrations.AlterField(
            model_name='pagelanguage',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Post', verbose_name='Post parent'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Post description'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='section',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='contents/sections/backgrounds', verbose_name='Section background image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True, verbose_name='Section background color'),
        ),
        migrations.AlterField(
            model_name='sectionlanguage',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
