# Generated by Django 2.2.3 on 2021-04-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('menus', '0003_auto_20210411_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitemlanguage',
            old_name='menu_item',
            new_name='menuitem',
        ),
        migrations.AlterUniqueTogether(
            name='menuitemlanguage',
            unique_together={('language', 'menuitem')},
        ),
    ]
