# Generated by Django 2.2.3 on 2021-04-29 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0004_auto_20210412_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.MenuItem', verbose_name='Menu item parent'),
        ),
        migrations.AlterField(
            model_name='menuitemlanguage',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Traducciones', to='menus.MenuItem'),
        ),
    ]
