# Generated by Django 2.2.3 on 2021-05-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_auto_20210422_2208'),
        ('menus', '0006_auto_20210504_2344'),
    ]

    operations = [
    ]
