# Generated by Django 2.2.3 on 2021-04-09 22:05 Updated by nigga 2021-03-14 14:17

import ckeditor.fields
import colorfield.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210409_1705'),
        ('contents', '0003_auto_20210328_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannergallery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bannergallery',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='bannerlanguage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bannerlanguage',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='bannerlanguage',
            name='language',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='contactlanguage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contactlanguage',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactlanguage',
            name='language',
        ),
        migrations.AlterUniqueTogether(
            name='galleryselector',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='galleryselector',
            name='banner_gallery',
        ),
        migrations.RemoveField(
            model_name='galleryselector',
            name='page',
        ),
        migrations.RemoveField(
            model_name='partnersgallery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='partnersgallery',
            name='home',
        ),
        migrations.RemoveField(
            model_name='partnersgallery',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='general_data',
        ),
        migrations.RemoveField(
            model_name='socialnetwork',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AlterModelOptions(
            name='sectionlanguage',
            options={'verbose_name': 'Section language', 'verbose_name_plural': 'Section languages'},
        ),
        migrations.AlterModelOptions(
            name='sectionselector',
            options={'ordering': ['order'], 'verbose_name': 'Select section', 'verbose_name_plural': 'Select sections'},
        ),
        migrations.AlterModelOptions(
            name='sectiontemplate',
            options={'verbose_name': 'Section template', 'verbose_name_plural': 'Section templates'},
        ),
        migrations.RemoveField(
            model_name='generaldata',
            name='logo_site',
        ),
        migrations.RemoveField(
            model_name='generaldata',
            name='slug_general_data',
        ),
        migrations.RemoveField(
            model_name='generaldata',
            name='title_one',
        ),
        migrations.RemoveField(
            model_name='generaldatalanguage',
            name='about',
        ),
        migrations.RemoveField(
            model_name='generaldatalanguage',
            name='general_metadata',
        ),
        migrations.RemoveField(
            model_name='generaldatalanguage',
            name='title_one',
        ),
        migrations.RemoveField(
            model_name='generaldatalanguage',
            name='title_two',
        ),
        migrations.RemoveField(
            model_name='page',
            name='gallery_selector',
        ),
        migrations.RemoveField(
            model_name='page',
            name='page_type',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug_page',
        ),
        migrations.RemoveField(
            model_name='pagelanguage',
            name='page_metadata',
        ),
        migrations.RemoveField(
            model_name='post',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='section',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_post',
        ),
        migrations.RemoveField(
            model_name='postgallery',
            name='image_360',
        ),
        migrations.RemoveField(
            model_name='postgallery',
            name='slug_post_gallery',
        ),
        migrations.RemoveField(
            model_name='postgallery',
            name='title_translation',
        ),
        migrations.RemoveField(
            model_name='postgallery',
            name='url_youtube',
        ),
        migrations.RemoveField(
            model_name='postlanguage',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='postlanguage',
            name='post_metadata',
        ),
        migrations.RemoveField(
            model_name='postlanguage',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='postlanguage',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='postlanguage',
            name='title_post',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description_visibility',
        ),
        migrations.RemoveField(
            model_name='section',
            name='gallery_visibility',
        ),
        migrations.RemoveField(
            model_name='section',
            name='lines_to_show',
        ),
        migrations.RemoveField(
            model_name='section',
            name='logo_visibility',
        ),
        migrations.RemoveField(
            model_name='section',
            name='page',
        ),
        migrations.RemoveField(
            model_name='section',
            name='slug_section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='subtitle_visibility',
        ),
        migrations.RemoveField(
            model_name='section',
            name='tag_visibility',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title_visibility',
        ),
        migrations.RemoveField(
            model_name='sectionlanguage',
            name='sect_metadata',
        ),
        migrations.AddField(
            model_name='generaldata',
            name='logo',
            field=models.ImageField(blank=True, upload_to='contents/site/logo', verbose_name='Site logo'),
        ),
        migrations.AddField(
            model_name='generaldatalanguage',
            name='footer',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Footer'),
        ),
        migrations.AddField(
            model_name='generaldatalanguage',
            name='main_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Menu', verbose_name='Main menu'),
        ),
        migrations.AddField(
            model_name='generaldatalanguage',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='-', verbose_name='Page slug'),
        ),
        migrations.AddField(
            model_name='pagelanguage',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Post link'),
        ),
        migrations.AddField(
            model_name='post',
            name='sections',
            field=models.ManyToManyField(through='contents.PostSettings', to='contents.Section'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='-', verbose_name='Post slug'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Post title'),
        ),
        migrations.AddField(
            model_name='postgallery',
            name='is_360',
            field=models.BooleanField(default=False, help_text='Check the box if is a 360 image', verbose_name='Is it a 360 image?'),
        ),
        migrations.AddField(
            model_name='postgallery',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Youtube video url'),
        ),
        migrations.AddField(
            model_name='postlanguage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Post description'),
        ),
        migrations.AddField(
            model_name='postlanguage',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='postlanguage',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Post title'),
        ),
        migrations.AddField(
            model_name='section',
            name='pages',
            field=models.ManyToManyField(through='contents.SectionSelector', to='contents.Page'),
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(default='-', verbose_name='Section slug'),
        ),
        migrations.AddField(
            model_name='sectionlanguage',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generaldata_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generaldata_updated_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='generaldatalanguage',
            name='general_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contents.GeneralData'),
        ),
        migrations.AlterField(
            model_name='generaldatalanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tools.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='page',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='page',
            name='inner_menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Menu', verbose_name='Page main menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Page', verbose_name='Page parent'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='Page title'),
        ),
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_updated_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='pagelanguage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Page description'),
        ),
        migrations.AlterField(
            model_name='pagelanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tools.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='pagelanguage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contents.Page'),
        ),
        migrations.AlterField(
            model_name='pagelanguage',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Page title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='icon',
            field=models.ImageField(blank=True, upload_to='contents/posts/icons', verbose_name='Post icon'),
        ),
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(blank=True, upload_to='contents/posts/logos', verbose_name='Post logo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Post', verbose_name='Post parent'),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_updated_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postgallery_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='contents/posts/galleries/panorama', verbose_name='Load image'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Post gallery name'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postgallery_updated_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tools.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contents.Post'),
        ),
        migrations.AlterField(
            model_name='postsettings',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Post'),
        ),
        migrations.AlterField(
            model_name='postsettings',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='background',
            field=models.ImageField(blank=True, upload_to='contents/sections/backgrounds', verbose_name='Section background image'),
        ),
        migrations.AlterField(
            model_name='section',
            name='background_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Section background color'),
        ),
        migrations.AlterField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='section',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='section',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.SectionTemplate', verbose_name='Section template'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='section',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_updated_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='sectionlanguage',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Section description'),
        ),
        migrations.AlterField(
            model_name='sectionlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tools.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='sectionlanguage',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contents.Section'),
        ),
        migrations.AlterField(
            model_name='sectionlanguage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Section title'),
        ),
        migrations.AlterField(
            model_name='sectionselector',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionselector_created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='sectionselector',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='sectionselector',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.Page'),
        ),
        migrations.AlterField(
            model_name='sectionselector',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.Section'),
        ),
        migrations.AlterField(
            model_name='sectionselector',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='sectionselector',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectionselector_updated_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='sectiontemplate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Template name'),
        ),
        migrations.AlterField(
            model_name='sectiontemplate',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Template nickname'),
        ),
        migrations.AlterField(
            model_name='sectiontemplate',
            name='preview',
            field=models.ImageField(blank=True, upload_to='contents/sections/templates', verbose_name='Template preview'),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='BannerGallery',
        ),
        migrations.DeleteModel(
            name='BannerLanguage',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactLanguage',
        ),
        migrations.DeleteModel(
            name='GallerySelector',
        ),
        migrations.DeleteModel(
            name='PartnersGallery',
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
