# Generated by Django 2.2.3 on 2021-04-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20210411_0119'),
        ('contents', '0005_auto_20210411_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldatalanguage',
            name='main_menu',
        ),
        migrations.AddField(
            model_name='generaldata',
            name='main_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Menu', verbose_name='Main menu'),
        ),
        migrations.AlterField(
            model_name='page',
            name='inner_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Menu', verbose_name='Page inner menu'),
        ),
    ]
