# Generated by Django 2.2.3 on 2021-04-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        ('contents', '0006_auto_20210412_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaldata',
            old_name='main_menu',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='generaldatalanguage',
            old_name='general_data',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='inner_menu',
            new_name='menu',
        ),
        migrations.AlterUniqueTogether(
            name='generaldatalanguage',
            unique_together={('language', 'info')},
        ),
    ]
