# Generated by Django 2.2.3 on 2021-05-05 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20210428_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemlanguage',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menus.MenuItem'),
        ),
    ]
