from django.utils.translation import ugettext_lazy as _

JSON_UPDATE_MESSAGE = _('JSON content updated')
LANGUAGE_TAB = _('Language')
MENU = _("Menu")
ACTIVE_KEY = "active"
MAIL_KEY = "mail"
NAME_KEY = "name"
MAIL = _("Mail")
DEFAULT_BOOL = True
DEFAULT_NUMBER = 0
AUDIT = _("Audit")
CREATED_BY_KEY = 'created_by'
UPDATED_BY_KEY = 'updated_by'
MENU_KEY = "menu"
EMPTY_VALUE = "-"
PARENT_KEY = "parent"
TITLE_KEY = "title"
NO_PAGES = _("It is not associated with any page")
IMAGE_PREVIEW = _("Preview")
SLUG_KEY = "slug"
URL_SEND = "send/"
URL_MAIL = f"{URL_SEND}main/"
IDS = "ids"
TOOLS_APP_LABEL = "tools"
MENUS_APP_LABEL = "menus"
MENU_NAME = _('Menu name')
MAX_LENGTH_NAME = 100
MAX_LENGTH_200 = 200
NAME = _("Name")
TEMPLATE = _("Template")
MENU_ITEM_NAME = _('Item name')
